import javax.swing.*;
public class AddBook extends javax.swing.JPanel {

 private Book_Management bookPanel;
    
    public AddBook(Book_Management bookPanel) {
        initComponents();
        this.bookPanel = bookPanel;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbGenre = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("AddBook");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 110, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Title:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Author:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("ISBN:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Quantity:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        txtTitle.setBackground(new java.awt.Color(255, 255, 153));
        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });
        jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 110, -1));

        txtAuthor.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.add(txtAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 110, -1));

        txtIsbn.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.add(txtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 110, -1));

        txtQuantity.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 110, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("ADD BOOK:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 102));
        jLabel7.setText("Genre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        cmbGenre.setBackground(new java.awt.Color(255, 255, 153));
        cmbGenre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbGenre.setForeground(new java.awt.Color(0, 0, 0));
        cmbGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "Romance", "Horror", "Mystery", "Fantasy" }));
        cmbGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGenreActionPerformed(evt);
            }
        });
        jPanel1.add(cmbGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 110, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yuu (2).png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 420, 510));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String title = txtTitle.getText();
     String author = txtAuthor.getText();
     String isbn = txtIsbn.getText();
     String genre = cmbGenre.getSelectedItem().toString();
   int quantity = Integer.parseInt(txtQuantity.getText());
     
     if(title.isEmpty() || author.isEmpty() || isbn.isEmpty()){
         JOptionPane.showMessageDialog(this, "Please fill all field");
         return;
     }
     if(quantity <= 0){
         JOptionPane.showMessageDialog(this,"Quantity Must be Greater than Zero!");
         return;
     }
     Book book = new Book(title,author,isbn,quantity,genre);
     boolean success = BookDAO.addBook(book);
     
      if(quantity <= 0){
         JOptionPane.showMessageDialog(this,"Quantity must Greater than Zero!");
     }
      
      if(cmbGenre.getSelectedIndex() == 1){
         JOptionPane.showMessageDialog(this,"Please Select a Genre!");
     }
      
     if(success){
         JOptionPane.showMessageDialog(this,"User Added Successfully!");
          new Staff_Management().setVisible(true);
          bookPanel.loadBooks();
           SwingUtilities.getWindowAncestor(this).dispose();
     }else{
         JOptionPane.showMessageDialog(this,"Failed TO Add User!");
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGenreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbGenre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
