
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


public class AddBorrower extends javax.swing.JPanel {

    private Borrower_Management borrowerPanel;


    public AddBorrower(Borrower_Management borrowerPanel ) {
        initComponents();
        this.borrowerPanel = borrowerPanel;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fname = new javax.swing.JTextField();
        EAddress = new javax.swing.JTextField();
        Addressy = new javax.swing.JTextField();
        ContactNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fname.setBackground(new java.awt.Color(255, 255, 153));
        add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 110, -1));

        EAddress.setBackground(new java.awt.Color(255, 255, 153));
        add(EAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 110, -1));

        Addressy.setBackground(new java.awt.Color(255, 255, 153));
        Addressy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressyActionPerformed(evt);
            }
        });
        add(Addressy, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 110, -1));

        ContactNumber.setBackground(new java.awt.Color(255, 255, 153));
        add(ContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 110, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Add Borrower");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Full Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Email Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Address:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("Contact Number:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yuu (2).png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 420, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void AddressyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = fname.getText();
        String email = EAddress.getText();
        String Address = Addressy.getText();
        String ContactN = ContactNumber.getText();
        
         if(name.isEmpty() || email.isEmpty() || Address.isEmpty() || ContactN.isEmpty()){
         JOptionPane.showMessageDialog(this, "Please fill all field");
         return;
     }
         if(!ContactN.matches("\\d{1,15}")){
    JOptionPane.showMessageDialog(this, "Contact Number must be numeric and maximum 15 digits");
    return;
}
          Borrower borrower = new Borrower(name,email,Address,ContactN);
     boolean success = borrowerDAO.addBorrower(borrower);
         
     if(success){
         JOptionPane.showMessageDialog(this,"Borrower Added Successfully!");
          new Staff_Management().setVisible(true);
          borrowerPanel.LoadBorrower();
           SwingUtilities.getWindowAncestor(this).dispose();
     }else{
         JOptionPane.showMessageDialog(this,"Failed TO Add User!");
     }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Addressy;
    private javax.swing.JTextField ContactNumber;
    private javax.swing.JTextField EAddress;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
