
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


public class BorrowedBook extends javax.swing.JPanel {

    private Staff_Frame Staffpanel;
    
    public BorrowedBook(Staff_Frame Staffpanel) {
        initComponents();
        this.Staffpanel = Staffpanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bkpin = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        brpin = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Borrowed Panel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 20));
        add(bkpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 110, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Staff Username:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("Id of the Book Borrowed:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtusername.setBackground(new java.awt.Color(255, 255, 153));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 110, -1));

        jButton1.setText("Confirm Borrowed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setText("Staff Password:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));
        add(brpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 110, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 102));
        jLabel8.setText("Id of the Borrower:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 169, -1, -1));

        txtpassword.setBackground(new java.awt.Color(255, 255, 153));
        add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 110, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yuu (2).png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 420, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     int BookId =(int) bkpin.getValue();
     int borrowerId =(int) brpin.getValue();
     String username = txtusername.getText();
     String password = new String (txtpassword.getPassword());
     
      if(username.isEmpty() || password.isEmpty()){
         JOptionPane.showMessageDialog(this,"Please enter the staff username and password to continue");
         return;
     }
      if(!username.equals(Staff_Frame.SaveUsername)){
         JOptionPane.showMessageDialog(this,"Staff username do not match!");
         return;
     }
      
      if(!password.equals(Staff_Frame.SavePassword)){
         JOptionPane.showMessageDialog(this,"Staff password do not match!");
         return;
     }
      Book book = BookDAO.getbyId(BookId);
      if(book == null){
          JOptionPane.showMessageDialog(this,"Book not found!");
          return;
      }
      
      Borrower borrower = borrowerDAO.getbyId(borrowerId);
      if(borrower == null){
          JOptionPane.showMessageDialog(this,"Borrower not found!");
          return;
      }
      
      if(!issuedBooksDAO.isAvailable(BookId)){
        JOptionPane.showMessageDialog(this,"This book is out of stock!");
        return;
    }
      
       if(issuedBooksDAO.hasBorrowed(borrowerId, BookId)){
        JOptionPane.showMessageDialog(this,"This borrower already borrowed this book!");
        return;
    }
    
   
      
    boolean success = issuedBooksDAO.borrowBook(BookId, borrowerId);
    if(success){
   JOptionPane.showMessageDialog(this,"Book borrowed successfully!");
          Staffpanel.loadBooks();
           SwingUtilities.getWindowAncestor(this).dispose();
} else {
    JOptionPane.showMessageDialog(this,"Borrow failed! The book might be out of stock.");
}
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner bkpin;
    private javax.swing.JSpinner brpin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
