
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eve
 */
public class DeleteBorrower extends javax.swing.JPanel {

        private Borrower_Management borrowerPanel;
    
    public DeleteBorrower(Borrower_Management borrowerPanel) {
        initComponents();
        this.borrowerPanel = borrowerPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        TxtPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("BorrowerName:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Staff Password:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        txtName.setBackground(new java.awt.Color(255, 255, 153));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, -1));

        TxtPass.setBackground(new java.awt.Color(255, 255, 153));
        add(TxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 130, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Delete Borrower");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jButton1.setText("Delete Borrower");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yuu (2).png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 420, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = txtName.getText();
        String StaffPass = new String (TxtPass.getPassword());
        
        if(name.isEmpty()){
         JOptionPane.showMessageDialog(this,"Please enter the staff username to delete!");
         return;
     }
        
           if(!StaffPass.equals(Staff_Frame.SavePassword)){
         JOptionPane.showMessageDialog(this,"password do not match!");
         return;
     }
           
      int confirm = JOptionPane.showConfirmDialog(this,"are you sure you want to delete this Borrower : " + name + "?", "Confirm Delete", JOptionPane.YES_OPTION);
           if(confirm != JOptionPane.YES_OPTION){
            return;
        }
           boolean success = borrowerDAO.delBorrower(name);
        if(success){
         JOptionPane.showMessageDialog(this,"User DELETED Successfully!");
     borrowerPanel.LoadBorrower();
     SwingUtilities.getWindowAncestor(this).dispose();
        }else{
         JOptionPane.showMessageDialog(this,"Failed TO DELETE User!");
     }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TxtPass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
