import javax.swing.*;
public class DeleteBook extends javax.swing.JPanel {

private Book_Management bookPanel;  
    
    public DeleteBook(Book_Management bookPanel) {
        initComponents();
        this.bookPanel = bookPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtAdpass = new javax.swing.JPasswordField();
        txtAuthor = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Deletebook");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 110, -1));

        txtAdpass.setBackground(new java.awt.Color(255, 255, 153));
        txtAdpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdpassActionPerformed(evt);
            }
        });
        add(txtAdpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 110, -1));

        txtAuthor.setBackground(new java.awt.Color(255, 255, 153));
        txtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorActionPerformed(evt);
            }
        });
        add(txtAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 110, -1));

        txtTitle.setBackground(new java.awt.Color(255, 255, 153));
        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });
        add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 110, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Author:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Book's Title:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("DELETE BOOK");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Admin's Password:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yuu (2).png"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 420, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdpassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String title = txtTitle.getText();
     String author = txtAuthor.getText();
        String adminpass = new String (txtAdpass.getPassword());
        
        if(title.isEmpty()){
         JOptionPane.showMessageDialog(this,"Please enter the Book'Title to delete!");
         return;
     }
        
        if(author.isEmpty()){
         JOptionPane.showMessageDialog(this,"Please enter the Book'Author to delete!");
         return;
     }
        
        if(!adminpass.equals(AdminFrame.SavePassword)){
         JOptionPane.showMessageDialog(this,"password do not match!");
         return;
     }
        
        int confirm = JOptionPane.showConfirmDialog(this,"are you sure you want to delete user: " + title + "by " + author + "?", "Confirm Delete", JOptionPane.YES_OPTION);
        
        if(confirm != JOptionPane.YES_OPTION){
            return;
        }
        
        boolean success = BookDAO.delBook(title, author);
        if(success){
         JOptionPane.showMessageDialog(this,"Book DELETED Successfully!");
         bookPanel.loadBooks();
           SwingUtilities.getWindowAncestor(this).dispose();
     }else{
         JOptionPane.showMessageDialog(this,"Failed TO DELETE Book!");
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void txtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtAdpass;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
