
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eve
 */
public class ReturnedBook extends javax.swing.JPanel {

   private Staff_Frame Staffpanel;
    
    public ReturnedBook(Staff_Frame Staffpanel) {
        initComponents();
        this.Staffpanel = Staffpanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        brspin = new javax.swing.JSpinner();
        txtusername = new javax.swing.JTextField();
        bkspin = new javax.swing.JSpinner();
        txtpassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Returned Confirmed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 383, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Book's ID:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Staff Username: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 261, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Staff Password:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 317, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Returned Panel");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("Borrower' ID:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        add(brspin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 149, -1));

        txtusername.setBackground(new java.awt.Color(255, 255, 153));
        add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 259, 149, -1));
        add(bkspin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 149, -1));

        txtpassword.setBackground(new java.awt.Color(255, 255, 153));
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 315, 148, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setText("Staff Confirmation");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yuu (2).png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 420, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int BookId =(int) bkspin.getValue();
     int borrowerId =(int) brspin.getValue();
     String username = txtusername.getText();
     String password = new String (txtpassword.getPassword());
     
     if(username.isEmpty() || password.isEmpty()){
         JOptionPane.showMessageDialog(this,"Please enter the staff username and password to continue");
         return;
     }
     
     if(!username.equals(Staff_Frame.SaveUsername)){
         JOptionPane.showMessageDialog(this,"Staff username do not match!");
         return;
     }
     
     if(!password.equals(Staff_Frame.SavePassword)){
         JOptionPane.showMessageDialog(this,"Staff password do not match!");
         return;
     }
     
     Book book = BookDAO.getbyId(BookId);
      if(book == null){
          JOptionPane.showMessageDialog(this,"Book not found!");
          return;
      }
      
      Borrower borrower = borrowerDAO.getbyId(borrowerId);
      if(borrower == null){
          JOptionPane.showMessageDialog(this,"Borrower not found!");
          return;
      }
      
      if(!issuedBooksDAO.hasBorrowedBook(BookId,borrowerId)){
        JOptionPane.showMessageDialog(this,"This Book is not borrowed by the Borrower!");
        return;
    }
      
       if(issuedBooksDAO.hasReturned(borrowerId, BookId)){
        JOptionPane.showMessageDialog(this,"This borrower already returned this book!");
        return;
    }
       
       boolean success = issuedBooksDAO.ReturnedBook(BookId, borrowerId);
    if(success){
   JOptionPane.showMessageDialog(this,"Book returned successfully!");
          Staffpanel.loadBooks();
           SwingUtilities.getWindowAncestor(this).dispose();
} else {
    JOptionPane.showMessageDialog(this,"returned failed! Something went wrong!.");
}
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner bkspin;
    private javax.swing.JSpinner brspin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
