import javax.swing.*;
public class UpdateStaff extends javax.swing.JPanel {

 private Staff_Management staffPanel;   
    
    public UpdateStaff(Staff_Management staffPanel) {
        initComponents();
        this.staffPanel = staffPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        cmbRole = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Sid = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yuu (2).png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jTextField2.setBackground(new java.awt.Color(255, 255, 153));

        jTextField1.setBackground(new java.awt.Color(255, 255, 153));

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Update Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Update Password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Update Role:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jButton1.setText("Click to Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("UPDATE STAFF");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        txtusername.setBackground(new java.awt.Color(255, 255, 153));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 130, -1));

        txtpass.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 218, 129, -1));

        cmbRole.setBackground(new java.awt.Color(255, 255, 153));
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "admin", "staff" }));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });
        jPanel1.add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 256, 129, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("ID of the User Want to Update:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 84, -1, -1));
        jPanel1.add(Sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 107, 50, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yuu (2).png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -10, 420, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int UserId =(int) Sid.getValue();
      String username = txtusername.getText();
      String password = new String (txtpass.getPassword());
      String role = cmbRole.getSelectedItem().toString();
      
      if(username.isEmpty() || password.isEmpty()){
         JOptionPane.showMessageDialog(this, "Please fill all field");
         return;
     }
       if(cmbRole.getSelectedIndex() == 0){
         JOptionPane.showMessageDialog(this,"Please Select a Role!");
         return;
     }
       User user = UserDAO.getbyId(UserId);
      if(user == null){
          JOptionPane.showMessageDialog(this,"User not found!");
          return;
      }
        user.setUsername(username);
       user.setPassword(password);
       user.setRole(role);
       
        boolean success = UserDAO.updUser(user);
        
        if(success){
         JOptionPane.showMessageDialog(this,"User Updated Successfully!");
         staffPanel.LoadUsers();
         SwingUtilities.getWindowAncestor(this).dispose();
     }else{
         JOptionPane.showMessageDialog(this,"Failed TO Add User!");
     }
       
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Sid;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
