import javax.swing.*;
public class UpdateBook extends javax.swing.JPanel {

 private Book_Management bookPanel;  
    
    
    public UpdateBook(Book_Management bookPanel) {
        initComponents();
        this.bookPanel = bookPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        updTitle = new javax.swing.JTextField();
        updAuthor = new javax.swing.JTextField();
        updIsbn = new javax.swing.JTextField();
        updQuantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbGenre = new javax.swing.JComboBox<>();
        Sid = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("UPDATE BOOK");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Title:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Author:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("ISBN:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("Quantity:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        updTitle.setBackground(new java.awt.Color(255, 255, 153));
        add(updTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 110, -1));

        updAuthor.setBackground(new java.awt.Color(255, 255, 153));
        add(updAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 110, -1));

        updIsbn.setBackground(new java.awt.Color(255, 255, 153));
        updIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updIsbnActionPerformed(evt);
            }
        });
        add(updIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 110, -1));

        updQuantity.setBackground(new java.awt.Color(255, 255, 153));
        add(updQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 110, -1));

        jButton1.setText("Update Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 110, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 102));
        jLabel7.setText("ID of the Book Want to Update:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setText("Genre:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 286, -1, -1));

        cmbGenre.setBackground(new java.awt.Color(255, 255, 153));
        cmbGenre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "Romance", "horror", "Mystery", "Fantasy" }));
        add(cmbGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 282, 110, -1));

        Sid.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Sid.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                SidAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        add(Sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 40, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yuu (2).png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 420, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void updIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updIsbnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int BookId =(int) Sid.getValue();
        String title = updTitle.getText();
      String author = updAuthor.getText();
      String isbn = updIsbn.getText();
      String quantityStr = updQuantity.getText();
      String genre = cmbGenre.getSelectedItem().toString();
      
      
      if(title.isEmpty() || author.isEmpty() || isbn.isEmpty()){
         JOptionPane.showMessageDialog(this, "Please fill all field");
         return;
     }
      int quantity;
      try{
          quantity = Integer.parseInt(quantityStr);
      if(quantity <= 0){
         JOptionPane.showMessageDialog(this,"Quantity must Greater than Zero!");
         return;
      }
      }catch(NumberFormatException e){
          JOptionPane.showMessageDialog(this,"Quantity must be a Number!");
          return;
      }
      
      Book book = BookDAO.getbyId(BookId);
      if(book == null){
          JOptionPane.showMessageDialog(this,"Book not found!");
          return;
      }
       
       book.setTitle(title);
       book.setAuthor(author);
       book.setGenre(genre);
       book.setIsbn(isbn);
       book.setQuantity(quantity);
       
        boolean success = BookDAO.updBook(book);
        
         if(cmbGenre.getSelectedIndex() == 1){
         JOptionPane.showMessageDialog(this,"Please Select a Genre!");
     }
        
        if(success){
         JOptionPane.showMessageDialog(this,"Book update Successfully!");
         bookPanel.loadBooks();
           SwingUtilities.getWindowAncestor(this).dispose();
     }else{
         JOptionPane.showMessageDialog(this,"Failed TO update Book!");
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SidAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_SidAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_SidAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Sid;
    private javax.swing.JComboBox<String> cmbGenre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField updAuthor;
    private javax.swing.JTextField updIsbn;
    private javax.swing.JTextField updQuantity;
    private javax.swing.JTextField updTitle;
    // End of variables declaration//GEN-END:variables
}
