
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eve
 */
public class UpdateBorrower extends javax.swing.JPanel {

    private Borrower_Management borrowerPanel;
    
    public UpdateBorrower(Borrower_Management borrowerPanel) {
        initComponents();
        this.borrowerPanel = borrowerPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Sid = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        txtcp = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Update Borrower");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));
        add(Sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 140, 40, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("UpdateBorrowerName:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("UpdateBorrowerEmail");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("UpdateBAddress");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("UpdateBContactNumber:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jButton1.setText("Confirm Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        txtname.setBackground(new java.awt.Color(255, 255, 153));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 120, -1));

        txtcp.setBackground(new java.awt.Color(255, 255, 153));
        add(txtcp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 120, -1));

        txtaddress.setBackground(new java.awt.Color(255, 255, 153));
        add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 120, -1));

        txtemail.setBackground(new java.awt.Color(255, 255, 153));
        add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 120, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 102));
        jLabel7.setText("ID of  the Borrower to update");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 97, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yuu (2).png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 420, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int BorrowerId =(int) Sid.getValue();
      String name = txtname.getText();
      String email = txtemail.getText();
      String Address = txtaddress.getText();
      String ContactN = txtcp.getText();

      if(name.isEmpty() || email.isEmpty() || Address.isEmpty() || ContactN.isEmpty()){
         JOptionPane.showMessageDialog(this, "Please fill all field");
         return;
     }
      
      if(!ContactN.matches("\\d{1,15}")){
    JOptionPane.showMessageDialog(this, "Contact Number must be numeric and maximum 15 digits");
    return;
}
      Borrower borrower = borrowerDAO.getbyId(BorrowerId);
      if(borrower == null){
          JOptionPane.showMessageDialog(this,"Borrower not found!");
          return;
      }
      
       borrower.setName(name);
       borrower.setEmail(email);
       borrower.setAddress(Address);
       borrower.setContactN(ContactN);
       
        boolean success = borrowerDAO.updBorrower(borrower);
        
        if(success){
         JOptionPane.showMessageDialog(this,"Borrower update Successfully!");
         borrowerPanel.LoadBorrower();
           SwingUtilities.getWindowAncestor(this).dispose();
     }else{
         JOptionPane.showMessageDialog(this,"Failed TO update Borrower!");
     }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Sid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtcp;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
